a=int(input("A="))
b=int(input("B="))
c=int(input("C="))
if(1<=a<=100000):
    sum=0;
    i=0;
    while(i,a):
            sum=sum+b
            b=b+c
            i=i+1
            print(sum)
    else:
            print("invalid")
